version: '3'
services:
  opsflow-orchestrator:
    container_name: opsflow-orchestrator
    restart: "always"
    build:
      context: ./opsflow-orchestrator
      dockerfile: Dockerfile
    image: opsflow-orchestrator
    environment:
      - RABBIT_URL=amqp://admin:admin@message-broker:5672
      - DB_USER=sa
      - DB_PASSWORD=password
      - DB_PORT=1433
      - DB_HOST=sql-server
      - DB_NAME=Opsflow
      - DB_CONNECTION_TIMEOUT=5000
      - DB_REQUEST_TIMEOUT=5000
    volumes:
      - ./opsflow-orchestrator:/app
    command: "npm run start:debug"
    ports:
      - 3000:8080
      - 9290:9229
    tty: true
    networks:
      - custom_network

  acehub-api:
    container_name: acehub-api
    restart: "always"
    build:
      context: ./acehub-api
      dockerfile: Dockerfile
    image: acehub-api
    environment:
      - RABBIT_URL=amqp://admin:admin@message-broker:5672
    volumes:
      - ./acehub-api:/app
    command: "npm run start:debug"
    ports:
      - 3001:8080
      - 9291:9229
    tty: true
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: payvision
