USE [master]
GO

/****** Object:  Database [OpsFlow]    Script Date: 5/12/2020 8:24:09 PM ******/
DROP DATABASE [OpsFlow]
GO

/****** Object:  Database [OpsFlow]    Script Date: 5/12/2020 8:24:09 PM ******/
CREATE DATABASE [OpsFlow]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OpsFlow', FILENAME = N'/var/opt/mssql/data/OpsFlow.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OpsFlow_log', FILENAME = N'/var/opt/mssql/data/OpsFlow_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OpsFlow].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OpsFlow] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OpsFlow] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OpsFlow] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OpsFlow] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OpsFlow] SET ARITHABORT OFF 
GO

ALTER DATABASE [OpsFlow] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OpsFlow] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OpsFlow] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OpsFlow] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OpsFlow] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OpsFlow] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OpsFlow] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OpsFlow] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OpsFlow] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OpsFlow] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OpsFlow] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OpsFlow] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OpsFlow] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OpsFlow] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OpsFlow] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OpsFlow] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OpsFlow] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OpsFlow] SET RECOVERY FULL 
GO

ALTER DATABASE [OpsFlow] SET  MULTI_USER 
GO

ALTER DATABASE [OpsFlow] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OpsFlow] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OpsFlow] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OpsFlow] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OpsFlow] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OpsFlow] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OpsFlow] SET  READ_WRITE 
GO


