version: '3'
services:
  message-broker:
    container_name: sql-server-orch
    build:
      context: .
      dockerfile: Dockerfile
    image: sql-server-orch
    environment:
      - SA_PASSWORD=paSSword1234!
      - PORT=9040
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports:
     - "9040:1433"
    networks:
     - custom_network   

networks:
  custom_network:
    external:
      name: payvision
